[package]
name = "hello-rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
dotenvy = "0.15.7"
reqwest = "0.12.5"
rocket = { version = "0.5", features = ["json"] }
serde = "1.0.208"
serde_json = "1.0.125"
tokio = "1.39.2"
